[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "braced-string-interpolation"
start_line = 98
end_line = 98

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "cyclomatic-complexity"
start_line = 27
end_line = 305

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "halstead"
start_line = 65
end_line = 144

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "kan-defect"
start_line = 27
end_line = 305

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "no-else-clause"
start_line = 120
end_line = 127

[[entries."src/Core/Config.php".issues]]
code = "cyclomatic-complexity"
start_line = 9
end_line = 180

[[entries."src/Core/Config.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 125
end_line = 125

[[entries."src/Core/Config.php".issues]]
code = "no-else-clause"
start_line = 170
end_line = 177

[[entries."src/Core/Container.php".issues]]
code = "no-else-clause"
start_line = 76
end_line = 78

[[entries."src/Core/System.php".issues]]
code = "no-redundant-use"
start_line = 10
end_line = 10

[[entries."src/Core/YamlParser.php".issues]]
code = "cyclomatic-complexity"
start_line = 12
end_line = 127

[[entries."src/Core/YamlParser.php".issues]]
code = "no-else-clause"
start_line = 81
end_line = 88

[[entries."src/Core/YamlParser.php".issues]]
code = "no-else-clause"
start_line = 102
end_line = 109

[[entries."src/Core/YamlParser.php".issues]]
code = "prefer-early-continue"
start_line = 84
end_line = 86

[[entries."src/Factory/ContainerFactory.php".issues]]
code = "prefer-early-continue"
start_line = 33
end_line = 38

[[entries."src/Router/RouteParser.php".issues]]
code = "cyclomatic-complexity"
start_line = 14
end_line = 165

[[entries."src/Router/RouteParser.php".issues]]
code = "kan-defect"
start_line = 14
end_line = 165

[[entries."src/Router/RouteParser.php".issues]]
code = "no-else-clause"
start_line = 107
end_line = 109

[[entries."src/Router/RouteParser.php".issues]]
code = "no-else-clause"
start_line = 111
end_line = 113

[[entries."src/Router/RouteParser.php".issues]]
code = "no-empty"
start_line = 45
end_line = 45

[[entries."src/Router/RouteParser.php".issues]]
code = "prefer-early-continue"
start_line = 136
end_line = 140

[[entries."src/Router/RouteParser.php".issues]]
code = "prefer-early-continue"
start_line = 159
end_line = 161

[[entries."src/Security/Rule/Level2Rule.php".issues]]
code = "prefer-early-continue"
start_line = 30
end_line = 35

[[entries."src/Security/Rule/Level5Rule.php".issues]]
code = "prefer-early-continue"
start_line = 30
end_line = 35

[[entries."src/Security/Rule/Level6Rule.php".issues]]
code = "prefer-early-continue"
start_line = 26
end_line = 31

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "no-redundant-use"
start_line = 7
end_line = 7

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "prefer-early-continue"
start_line = 83
end_line = 85

[[entries."src/Trait/RequestTrait.php".issues]]
code = "no-redundant-use"
start_line = 6
end_line = 6

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "no-redundant-use"
start_line = 6
end_line = 6

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "no-redundant-use"
start_line = 7
end_line = 7

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "no-redundant-use"
start_line = 8
end_line = 8

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "no-redundant-use"
start_line = 9
end_line = 9

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "no-redundant-use"
start_line = 10
end_line = 10

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "prefer-early-continue"
start_line = 37
end_line = 39

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "prefer-early-continue"
start_line = 65
end_line = 67

[[entries."tests/src/Abstract/AbstractKernelTest.php".issues]]
code = "no-else-clause"
start_line = 340
end_line = 344

[[entries."tests/src/Abstract/AbstractKernelTest.php".issues]]
code = "no-redundant-use"
start_line = 13
end_line = 13

[[entries."tests/src/Abstract/AbstractKernelTest.php".issues]]
code = "too-many-methods"
start_line = 19
end_line = 95

[[entries."tests/src/Abstract/AbstractKernelTest.php".issues]]
code = "too-many-methods"
start_line = 97
end_line = 177

[[entries."tests/src/Abstract/Helper/ConcreteTestKernel.php".issues]]
code = "no-redundant-use"
start_line = 6
end_line = 6

[[entries."tests/src/Cache/RouteCacheTest.php".issues]]
code = "no-else-clause"
start_line = 49
end_line = 51

[[entries."tests/src/Core/ConfigTest.php".issues]]
code = "no-redundant-use"
start_line = 7
end_line = 7

[[entries."tests/src/Core/ConfigTest.php".issues]]
code = "no-redundant-use"
start_line = 9
end_line = 9

[[entries."tests/src/Core/ConfigTest.php".issues]]
code = "prefer-early-continue"
start_line = 84
end_line = 86

[[entries."tests/src/Core/ConfigTest.php".issues]]
code = "too-many-methods"
start_line = 17
end_line = 294

[[entries."tests/src/Core/ContainerTest.php".issues]]
code = "prefer-static-closure"
start_line = 129
end_line = 129

[[entries."tests/src/Core/ContainerTest.php".issues]]
code = "too-many-methods"
start_line = 33
end_line = 240

[[entries."tests/src/Core/Helper/SystemTestKernel.php".issues]]
code = "no-else-clause"
start_line = 30
end_line = 33

[[entries."tests/src/Core/SystemTest.php".issues]]
code = "explicit-octal"
start_line = 29
end_line = 29

[[entries."tests/src/Helper/Security/Rule3ValidObject1.php".issues]]
code = "no-protected-in-final"
start_line = 19
end_line = 19

[[entries."tests/src/Helper/Security/Rule7ValidObject.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 8
end_line = 8

[[entries."tests/src/Router/ControllerFinderTest.php".issues]]
code = "explicit-octal"
start_line = 25
end_line = 25

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "no-else-clause"
start_line = 60
end_line = 65

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "prefer-early-continue"
start_line = 93
end_line = 99

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "prefer-early-continue"
start_line = 117
end_line = 120

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "prefer-early-continue"
start_line = 140
end_line = 143

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "prefer-early-continue"
start_line = 170
end_line = 173

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "too-many-methods"
start_line = 19
end_line = 274

[[entries."tests/src/Trait/ReflectionTraitTest.php".issues]]
code = "no-error-control-operator"
start_line = 117
end_line = 117

[[entries."tests/src/Trait/ReflectionTraitTest.php".issues]]
code = "prefer-static-closure"
start_line = 141
end_line = 141

[[entries."tests/src/Trait/ReflectionTraitTest.php".issues]]
code = "too-many-methods"
start_line = 20
end_line = 219

[[entries."tests/src/Trait/SecurityTraitTest.php".issues]]
code = "too-many-methods"
start_line = 19
end_line = 246
